[pytest]
addopts = --basetemp=.tmp/pytest
testpaths = tests
norecursedirs = .tmp .test_tmp .test_tmp2 .test_tmp3 manual_tmp pytest-cache-files-* test_run_tmp venv raw_data outputs processed_data datasets logs
